### ISSUE TITLE
Code on RPi Pico

### ISSUE THREAD

**Issue by ebolisa** [n-elia/MAX30102-MicroPython-driver#4]
Hi, 
Testing the library code (no changes made) on a Pico board and getting pretty much a linear output.
What is possible wrong?
TIA

![Cap](https://user-images.githubusercontent.com/17126140/118961919-20ea6600-b965-11eb-85ad-1ff1c9f8c218.PNG)

**Comment by n-elia** [comment]
Hi ebolisa!
First of all, let me know which is your particular board, and which is your sensor (the original Maxim, or a clone?).
Then, please try to scale the y-axis, e.g., plot the _Columna B_ only with an y-axis ranging from 18000 to 22000.
Thank you!

**Comment by ebolisa** [comment]
Thanks for getting back to me.
I'm using the Raspberry Pi Pico and the sensor board may be a clone: https://pekolibrary.wordpress.com/2018/05/27/rcwl-0530-max30100/#more-3.
As for the graph, I'm using OpenOffice and I don't control it that well so I'm attaching some raw data.
[data.csv](https://github.com/n-elia/MAX30102-MicroPython-driver/files/6517216/data.csv)
![Cap](https://user-images.githubusercontent.com/17126140/119010067-fb288580-b993-11eb-86dd-d422bbc0addc.PNG)

**Comment by ebolisa** [comment]
Ok, Made progress. Had a crash course on Calc.
But how do I output in a range from 0 to 100% for Oxy. And < 200 for HR?
TIA

**Comment by n-elia** [comment]
Nice to see that it works well!

You have to do some math to obtain SpO2 and HR. I put some hints in the last lines of the readme, [here](https://github.com/n-elia/MAX30102-MicroPython-driver#other-things-that-its-worth-mentioning).

Please share your code if you manage to perform those computations locally, I am interested, too!

**Comment by ebolisa** [comment]
Sorry, I posted the wrong sensor's link so, I update my post.

**Comment by ebolisa** [comment]
Will do. Thanks again.
